# This is a basic workflow to help you get started with Actions

name: update image

on:
  schedule:
    - cron: '10 10 * * *'
  workflow_dispatch: {}

jobs:
  update-image:
    runs-on: ubuntu-18.04
    env:
      GROOVY_VERSION: 3.0.3

    steps:
    - name: setup Java
      uses: actions/setup-java@v1.4.3
      with:
        java-version: '11'

    - uses: actions/checkout@v2
      name: checkout

    - name: Cache
      uses: actions/cache@v1.1.2
      with:
        path: ~/groovy
        key: ${{ env.GROOVY_VERSION }}

    - name: check cache
      id: groovy
      run: |
        if [ -x ~/groovy/groovy-${GROOVY_VERSION}/bin/groovy ] ; then
          echo "groovy found"
          echo "::set-output name=install_required::no"
        else
          echo "groovy not found"
          echo "::set-output name=install_required::yes"
        fi

    - name: confirm configuration
      run: |
        echo "install : ${INSTALL_REQUIRED}"
        echo "GROOVY : ${GROOVY_HOME}"
      env:
        INSTALL_REQUIRED: ${{ steps.groovy.outputs.install_required }}

    - name: install groovy
      if: startsWith(steps.groovy.outputs.install_required, 'yes')
      run: |
        curl -L "https://dl.bintray.com/groovy/maven/apache-groovy-binary-${GROOVY_VERSION}.zip" -o ~/groovy.zip
        unzip -q ~/groovy.zip -d ~/groovy

    - name: set PATH
      run: echo "::add-path::${HOME}/groovy/groovy-${GROOVY_VERSION}/bin"

    - name: set GROOVY_HOME
      run: echo "GROOVY_HOME=${HOME}/groovy-${GROOVY_VERSION}" >> $GITHUB_ENV

    - name: show github env
      run: echo "${GITHUB_ENV}"

    - name: date
      id: date
      run: |
        now=$(date '+%Y-%m-%d')
        echo "::set-output name=value::${now}"

    - name: run script
      run: groovy ./plot.groovy

    - name: commit and push
      uses: stefanzweifel/git-auto-commit-action@v4.1.6
      with:
        commit_message: Auto ${{ steps.date.outputs.value }}

